version: '3.8'

services:
  frontend:
    build: ./client
    container_name: voice_frontend
    restart: always
    ports:
      - "3000:80"  # Optional: expose for debugging
    depends_on:
      - backend

  backend:
    build: ./server
    container_name: voice_backend
    restart: always
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/voiceanalyzer
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: voice_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:alpine
    container_name: voice_proxy
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - frontend
      - backend

volumes:
  mongo_data: