# Generated by Django 4.2.16 on 2026-04-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputText', models.TextField()),
                ('outputText', models.TextField()),
                ('mostFrequentlyUsedWord', models.CharField(max_length=500)),
                ('uniqueWords', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
