# Generated by Django 4.2.16 on 2026-04-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='hindiText',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='transcription',
            name='inputLang',
            field=models.CharField(default='ta', max_length=10),
        ),
    ]
